apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigip02
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=CHANGEME
        - --bigip-partition=openshift
        - --pool-member-type=cluster
        - --log-as3-response=true
        - --as3-validation=true
        - --extended-spec-configmap=kube-system/global-cis-cm
        - --log-level=DEBUG
        - --insecure=true
        - --disable-teems=true
        - --controller-mode=openshift
        - --orchestration-cni=ovn-k8s
        - --static-routing-mode=true
        - --shared-static-routes=true
        - --route-label=f5route
        - --namespace-label=f5_route=true
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        image: registry.connect.redhat.com/f5networks/cntr-ingress-svcs:2.15.1-ubi9
        imagePullPolicy: IfNotPresent
        name: cntr-ingress-svcs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bigip-login
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      terminationGracePeriodSeconds: 30
