apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-hub-placement
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: local-cluster
            operator: NotIn
            values:
             - "true"
             - "True"